"""Added Time Listing Feature For Artist.

Revision ID: 907e13677373
Revises: 37c62a0ae1a0
Create Date: 2022-06-03 09:10:36.907392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907e13677373'
down_revision = '37c62a0ae1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('start_availability', sa.DateTime(), nullable=True))
    op.add_column('artists', sa.Column('end_availability', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'end_availability')
    op.drop_column('artists', 'start_availability')
    # ### end Alembic commands ###
